### ISSUE TITLE
Cloud animation and 100% CPU

### ISSUE THREAD

**Issue by erkie** [linode/styles#5]
The cloud animation in the header on the blog causes CPU usage to spike to 100% on my Macbook Pro 2015, Chrome, El Capitan. Switching it off fixes this problem.

<img width="509" alt="screenshot 2016-06-23 08 04 31" src="https://cloud.githubusercontent.com/assets/21059/16285432/6d94fa28-3919-11e6-9a78-c5774ce59647.png">

While nice, I think it was pretty fine to disable it. The clouds had a much more serene feel to them when static :)

<img width="516" alt="screenshot 2016-06-23 08 05 42" src="https://cloud.githubusercontent.com/assets/21059/16285457/8d66c750-3919-11e6-9559-c9e5c64d4a3c.png">

**Comment by ddevault** [comment]
This has already been done, but the blog repo isn't using the latest styles (there are some breaking changes so I keep putting it off). Please file an issue on the blog (and maybe even a pull request?)
